name: Extrator de Ferias 2026

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install pypdf==5.1.0

      - name: Executar script de extração
        run: python extractr.py

      - name: Fazer upload do CSV resultante
        uses: actions/upload-artifact@v4
        with:
          name: provisao-extraida
          path: provisao_ferias.csv
