name: Executar Extracao de Ferias

on:
  workflow_dispatch: # Permite rodar manualmente clicando em um botão

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Rodar script
        run: python extrair_ferias.py
      - name: Upload do Resultado
        uses: actions/upload-artifact@v3
        with:
          name: csv-ferias-extraido
          path: provisao_ferias.csv
